# Write a Python program to count the frequency of words in a file.

with open("demo.txt", mode="r") as f:
  # f.read() is a single string. split the string into a list by the whitespace.
  # 'words' is now a list of all the words in the file content.
  words = f.read().split()
  word_fren = {word: words.count(word) for word in words}


print(word_fren)
# {'What': 1, 'is': 8, 'Python': 3, 'language?': 1, 'a': 6, 'widely': 1, 'used': 1, 'high-level,': 1, 'general-purpose,': 1, 'interpreted,': 1, 'dynamic': 2, 'programming': 3, 'language.Its': 1, 'design': 2, 'philosophy': 1, 'emphasizes': 1, 'code': 4, 'readability,': 1, 'and': 8, 'its': 1, 'syntax': 1, 'allows': 1, 'programmers': 1, 'to': 3, 'express': 1, 'concepts': 1, 'in': 3, 'fewer': 1, 'lines': 1, 'of': 4, 'than': 1, 'possible': 1, 'languages': 1, 'such': 1, 'as': 1, 'C++': 1, 'or': 4, 'Java.': 1, 'supports': 1, 'multiple': 1, 'paradigms,': 1, 'including': 1, 'object-oriented,': 1, 'imperative': 1, 'functional': 1, 'procedural': 1, 'styles.': 1, 'It': 2, 'features': 1, 'type': 1, 'system': 1, 'automatic': 1, 'memory': 1, 'management': 1, 'has': 1, 'large': 1, 'comprehensive': 1, 'standard': 1, 'library.The': 1, 'best': 1, 'way': 1, 'we': 1, 'learn': 1, 'anything': 1, 'by': 1, 'practice': 1, 'exercise': 1, 'questions.': 1, 'We': 1, 'have': 1, 'started': 1, 'this': 1, 'section': 1, 'for': 3, 'those': 1, '(beginner': 1, 'intermediate)': 1, 'who': 1, 'are': 1, 'familiar': 1, 'with': 2, 'Python.': 1, 'Depending': 1, 'on': 1, 'the': 8, 'project,': 1, 'your': 2, 'documentation': 2, 'might': 1, 'include': 2, 'some': 2, 'all': 2, 'following': 1, 'components:': 1, 'An': 2, 'introduction': 1, 'should': 2, 'give': 1, 'very': 1, 'short': 1, 'overview': 1, 'what': 1, 'can': 2, 'be': 1, 'done': 1, 'product,': 1, 'using': 1, 'one': 1, 'two': 1, 'extremely': 1, 'simplified': 1, 'use': 2, 'cases.': 1, 'This': 3, 'thirty-second': 1, 'pitch': 1, 'project.': 2, 'A': 1, 'tutorial': 1, 'show': 1, 'primary': 1, 'cases': 1, 'more': 1, 'detail.': 1, 'The': 1, 'reader': 1, 'will': 2, 'follow': 1, 'step-by-step': 1, 'procedure': 1, 'set-up': 1, 'working': 1, 'prototype.': 1, 'API': 1, 'reference': 1, 'typically': 1, 'generated': 1, 'from': 1, '(see': 1, 'docstrings).': 1, 'list': 1, 'publicly': 1, 'available': 1, 'interfaces,': 1, 'parameters,': 1, 'return': 1, 'values.': 1, 'Developer': 1, 'intended': 1, 'potential': 1, 'contributors.': 1, 'convention': 1, 'general': 1, 'strategy': 1, 'New': 1, 'line': 1, 'appended': 1, 'at': 1, 'end.': 1, 'current': 1, 'last': 1, 'line.': 1}